### ISSUE TITLE
etcd role works only from root

### ISSUE THREAD

**Issue by ReSearchITEng** [mbert/kubeadm2ha#17] opened 2018-09-14 11:59 UTC
If the playbook is run without root, the etcd role fails due to lack of perms. when it tries to copy the certs from localhost to all etcd machines: https://github.com/mbert/kubeadm2ha/blob/a89c719abddac62039fd699c676db9ce89f86c6d/ansible/roles/etcd/tasks/main.yaml#L64

Reason being: at unarchive, all files are owned by root (as they were on the primary-etcd), and now, a non-root user on control machine (localaction) cannot read them.

- Ugly work around: just add mode=0755 at the unarchive localaction: https://github.com/mbert/kubeadm2ha/blob/a89c719abddac62039fd699c676db9ce89f86c6d/ansible/roles/etcd/tasks/main.yaml#L60
- Ideally, split the certs.tar.gz archive in 2 archives: one for kubeadmcfg.yaml, one certificates.
Once there are 2 archives, there is no need to unarchive on the control machine, but let ansible transfer the archive from local control machine to the destination and unarchive there, with the right perms.

**Comment by mbert** [comment] 2018-10-28 07:27
I cannot reproduce this, and your conclusion does not seem valid to me: when you unarchive something as non-root user, the unarchiver (running with your local user's privileges) _cannot_ change file ownership to _root_, this is simply impossible, because as a non-root user you simply are not allowed to do so. My guess is that you may have had leftover files belonging to root on your local machine?

I'm closing this for now. Feel free to reopen it if you can show me how to reproduce the problem.

**Closed as completed by mbert** 2018-10-28 07:27 UTC
